config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :user_phones
  resources :user_adresses
  resources :reviews
  resources :order_items
  resources :orders
  resources :categories
  resources :cards
  resources :authors
  resources :users
  resources :tests
  resources :models
  resources :books
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
=begin
      t.string :first_name
      t.string :second_name
      t.text :description
      t.boolean :is_active
=end
class Author < ApplicationRecord
  has_many :books
end

app/models/book.rb
=begin
      t.string :title
      t.text :description
      t.decimal :price
      t.boolean :is_active
=end
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :category
end

app/models/card.rb
=begin
      t.string :number
      t.string :name
      t.string :mm
      t.string :yy
      t.string :cvv
=end
class Card < ApplicationRecord
  has_one :user
end

app/models/category.rb
=begin
      t.string :title
      t.text :description
      t.boolean :is_active
=end
class Category < ApplicationRecord
  has_many :books
end

app/models/order.rb
=begin
      t.string :number
      t.timestamps :date
=end
class Order < ApplicationRecord
  belongs_to :user, optional: true
  has_many :order_items
end

app/models/order_item.rb
=begin
      t.decimal :price
	  t.decimal :quantity
=end
class OrderItem < ApplicationRecord
  has_one :book
end

app/models/review.rb
=begin
	  t.string :title
	  t.string :description
      t.timestamp :date
=end
class Review < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :book, optional: true
end

app/models/user.rb
=begin
      t.string :first_name
      t.string :email
      t.string :password
      t.string :confirmation
      t.boolean :is_admin
=end

class User < ApplicationRecord
  has_many :orders
  has_many :cards
  has_many :phones
  has_many :user_adresses
  has_many :reviews
  validates :first_name, :password, :confirmation, presence: true
  validates :email, presence: true     
end

app/models/user_adress.rb
=begin
      t.string :adress
      t.string :city
      t.string :zip
      t.boolean :is_active
=end
class UserAdress < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user_phone.rb
=begin
      t.string :phone
      t.boolean :is_active
=end
class UserPhone < ApplicationRecord
  belongs_to :user, optional: true
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.fetch(:book, {})
    end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.fetch(:card, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/user_phones_helper.rb
module UserPhonesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.haml
= form_for @book do |f|
  - if @book.errors.any?
    #error_explanation
      %h2= "#{pluralize(@book.errors.count, "error")} prohibited this book from being saved:"
      %ul
        - @book.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/books/edit.html.haml
%h1 Editing book

= render 'form'

= link_to 'Show', @book
\|
= link_to 'Back', books_path

app/views/books/index.html.haml
%h1 Listing books

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @books.each do |book|
      %tr
        %td= link_to 'Show', book
        %td= link_to 'Edit', edit_book_path(book)
        %td= link_to 'Destroy', book, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Book', new_book_path

app/views/books/new.html.haml
%h1 New book

= render 'form'

= link_to 'Back', books_path

app/views/books/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_book_path(@book)
\|
= link_to 'Back', books_path

app/views/cards/_form.html.haml
= form_for @card do |f|
  - if @card.errors.any?
    #error_explanation
      %h2= "#{pluralize(@card.errors.count, "error")} prohibited this card from being saved:"
      %ul
        - @card.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/cards/edit.html.haml
%h1 Editing card

= render 'form'

= link_to 'Show', @card
\|
= link_to 'Back', cards_path

app/views/cards/index.html.haml
%h1 Listing cards

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @cards.each do |card|
      %tr
        %td= link_to 'Show', card
        %td= link_to 'Edit', edit_card_path(card)
        %td= link_to 'Destroy', card, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Card', new_card_path

app/views/cards/new.html.haml
%h1 New card

= render 'form'

= link_to 'Back', cards_path

app/views/cards/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_card_path(@card)
\|
= link_to 'Back', cards_path